#!/usr/bin/env sh

# Check required environment variables
if [ -z "$DT_ENVIRONMENT_ID" ]; then
    echo "Error: Environment variable DT_ENVIRONMENT_ID is not set." >&2
    exit 1
fi

if [ -z "$DT_PAAS_TOKEN" ]; then
    echo "Error: Environment variable DT_PAAS_TOKEN is not set." >&2
    exit 1
fi

if pgrep oneagentos > /dev/null
then
    echo "Dynatrace OneAgent is already running"
else
    sudo mkdir -p /var/lib/dynatrace
    sudo mkdir -p /opt/dynatrace/oneagent/
    sudo chown -R gitpod:gitpod /opt/dynatrace /var/lib/dynatrace

    wget -O /opt/dynatrace/oneagent/oneagent.sh "https://${DT_ENVIRONMENT_ID}.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=${DT_PAAS_TOKEN}&arch=x86&flavor=default"
    chmod +x /opt/dynatrace/oneagent/oneagent.sh

    sudo /opt/dynatrace/oneagent/oneagent.sh \
        USER=gitpod \
        GROUP=gitpod \
        --set-monitoring-mode=fullstack \
        --set-host-group=gitpod \
        --set-host-name="gitpod-${GITPOD_WORKSPACE_ID}-${GITPOD_INSTANCE_ID}" \
        --set-network-zone=gitpod
fi 

/ide/node "$@"